### ISSUE TITLE
model.py文件问题

### ISSUE THREAD

**Issue by BlueSkyBubble** [HandsomeCao/Bert-BiLSTM-CRF-pytorch#1]
好像在整个训练过程中并没有用到model.py文件，然而finetuning的逻辑是写在model.py文件中的，所以整个训练过程并没有实现finetuning功能。不知这样理解对不对？

**Comment by HandsomeCao** [comment]
在main.py里导入了model.py中定义的Net了

**Comment by cooscao** [comment]
在model.py里，是直接使用bert进行微调的，并没有加crf什么的。而crf.py里，是只取了bert最后一层的输出，作为句子的embedding，再输入到标准的bilstm-crf模型的，bert是没有参与训练的。
