### ISSUE TITLE
more elaborations on the whole pipeline?

### ISSUE THREAD

**Issue by IbtihalFerwana** [HandsomeCao/Bert-BiLSTM-CRF-pytorch#2]
Hi! :)

Your work attracted my attention, and I want to follow your approach for my use case

If you do not mind, I have questions:
- Do you have any paper/article/repo/blog you depended on to create this work?
- Can you breifly elaborate on your work flow, what is your pipeline, how did you order the layers and models?

Thanks

**Comment by cooscao** [comment]
Hello, there.
You can find something useful in this [rep](https://github.com/macanv/BERT-BiLSTM-CRF-NER). I was inspired by it.
