### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by rajae-Bens** [HandsomeCao/Bert-BiLSTM-CRF-pytorch#4]
Hi 

First, thank u for having shared ur code with us
I tried to execute ur code on google colab but it gave me this error even if CUDA is activated 

![Screen Shot 2020-11-23 at 9 28 31 AM](https://user-images.githubusercontent.com/58187895/99941439-50c9ff80-2d6e-11eb-8390-5aa0a3728b4d.png)

do u have any ideas plz?
thank u

**Comment by marcusau** [comment]
Did u change the setup from cpu to GPu in colab already ???

**Comment by rajae-Bens** [comment]
yes I did

**Comment by cooscao** [comment]
maybe you choose the wrong gpu number, try to change the os.environ

rajae-Bens <notifications@github.com> 于 2020年11月24日周二 00:06写道：
