### ISSUE TITLE
bert一直报错

### ISSUE THREAD

**Issue by kindofking** [HandsomeCao/Bert-BiLSTM-CRF-pytorch#8]
Model name 'model/bert-base-chinese' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'model/bert-base-chinese\vocab.txt' was a path or url but couldn't find any file associated to this path or url.

**Comment by SomeoneNotLikeYou** [comment]
我也和你一样 是同一个错误

**Comment by l-i-p-f** [comment]
我是网络限制，自己[手动下载](https://huggingface.co/bert-base-chinese/tree/main)的模型。
`self.bert = BertModel.from_pretrained(config.BertModelPath)` 
把 `from_pretrained` 里的参数改为本地`bert`模型路径

**Comment by cooscao** [comment]
> 我是网络限制，自己[手动下载](https://huggingface.co/bert-base-chinese/tree/main)的模型。
> `self.bert = BertModel.from_pretrained(config.BertModelPath)`
> 把 `from_pretrained` 里的参数改为本地`bert`模型路径

transformers版本为0.6.1，试试呢
